### ISSUE TITLE
Roadmap 1.0

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana-infinity-datasource#239]
# Infinity datasource roadmap

## v0.9.0

- [x] Support for [GROQ query language](https://www.sanity.io/docs/groq)
- [x] Filter data with UQL
- [x] #196 
- [x] Show corresponding curl command in Query inspector
- [x] Forward OAuth identity support

## v0.10.0

- [x] ~Client side query caching~
- [x] ~In JSON, Add support to access fields outside array~ ( use UQL instead )
- [x] Dynamic interval variable
- [x] Migrate string based legacy variables

## v.1.0.0

- [x] OAuth support
- [x] Basic/experimental backend support for common JSON formats.
   - [x] Alerting
   - [x] Expressions
   - [x] Recorded queries

**Comment by arpitgold** [comment]
Hi @yesoreyeram,
Thanks for the nice plugin....

I am interested in feature "Filter data with UQL" tagged in v0.9

If v0.9 and v10.0 all tasks are done.... do you have any plans to release these versions?
Or what is the timeline of v1.0.0?

**Comment by marcoboffi** [comment]
Hi @yesoreyeram ,
I m using UQL in several panel. It s very usefull!

When will UQL be available on backend to use it for alert rules?
