### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana-infinity-datasource#530]
# Infinity data source plugin roadmap

## potential candidates for upcoming versions

- [ ] token refresh authentication
- [ ] prom/loki agent
- [ ] local time-shift
- [ ] Join results from multiple APIs

## Version 2.0.0

- [x] https://github.com/yesoreyeram/grafana-infinity-datasource/discussions/601
- [x] https://github.com/yesoreyeram/grafana-infinity-datasource/discussions/614
- [x] move backend experimental features out of beta

## Version 1.0.0

- [x] OAuth support
- [x] Basic/experimental backend support for common JSON formats
- [x] Support for Grafana unified Alerting
- [x] Support for Grafana Server Side Expressions
- [x] Support for Grafana Recorded queries

## Version 0.10.0

- [x] ~Client side query caching~
- [x] ~In JSON, Add support to access fields outside array~ ( use UQL instead )
- [x] Dynamic interval variable
- [x] Migrate string based legacy variables

## Version 0.9.0

- [x] Support for [GROQ query language](https://www.sanity.io/docs/groq)
- [x] Filter data with UQL
- [x] #196 
- [x] Show corresponding curl command in Query inspector
- [x] Forward OAuth identity support

**Comment by ebachman24** [comment]
Being able to handle paginated results would be incredible.  Great work!  looking forward to it.

**Comment by gdiana** [comment]
The backend stuff is great well done and many thanks.

I saw a GRAFANA post that looked at being able to update the backend csv file to import added new data. Can this be done or is it already available under the GRAFAN update source feature?
