### ISSUE TITLE
Infinity plugin - migration epic

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana-infinity-datasource#717]
This epic details the action items required to the complete the plugin ownership changes.

```[tasklist]
### Migration tasklist
- [x] Change the repository ownership from `yesoreyeram` to `grafana`
- [x] Change Github references of old repo to new repo
- [x] Publish an intermediate version with the fix for broken links
- [x] Migrate from `grafana-toolkit` to `plugin-tools` ( this will also help to upgrade to node18+ ) https://github.com/grafana/grafana-infinity-datasource/pull/730
- [x] Migrate the plugin signature from `Community` to `Grafana Labs`
- [x] Migrate from `github actions` to `drone` to make it compatible with other plugins https://github.com/grafana/grafana-infinity-datasource/pull/719
- [x] Migrate the docs from [github pages](https://grafana.github.io/grafana-infinity-datasource/) to [grafana docs](https://grafana.com/docs/plugins/) https://github.com/grafana/grafana-infinity-datasource/pull/732
- [x] Publish a new version using drone
- [x] [Blogpost with the changes](https://grafana.com/blog/2024/02/05/infinity-plugin-for-grafana-grafana-labs-will-now-maintain-the-versatile-data-source-plugin/)
```

```[tasklist]
### Hand-over sessions
- [x] Session 1: Exploring the plugin features - ( JSON/GraphQL/CSV/XML/JSON/Misc )
- [x] Session 2: Exploring the plugin configuration and auth setup
- [x] Session 3: Walk-through of development, build process
- [x] Session 4: Exploring different parsers ( frontend, UQL, backend, groq )
- [x] Session 5: Prioritising upcoming features, discussing known issues
```
